"""

Revision ID: 0342_service_broadcast_settings
Revises: 0341_new_letter_rates
Create Date: 2021-01-28 21:30:23.102340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0342_service_broadcast_settings'
down_revision = '0341_new_letter_rates'

CHANNEL_TYPES = ["test", "severe"]


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###

def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  pass
  # ### end Alembic commands ###
