"""

Revision ID: 0344_stubbed_not_nullable
Revises: 0343_org_billing_details
Create Date: 2021-02-08 18:10:15.533279

"""
from alembic import op
import sqlalchemy as sa


revision = '0344_stubbed_not_nullable'
down_revision = '0343_org_billing_details'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
