"""
Revision ID: 0363_cancelled_by_api_key
Revises: 0362_broadcast_msg_event
Create Date: 2022-02-09 14:05:27.750234
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0363_cancelled_by_api_key'
down_revision = '0362_broadcast_msg_event'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
