"""empty message

Revision ID: 0375_fix_service_name
Revises: 0374_fix_reg_template_history
Create Date: 2022-08-29 11:04:15.888017

"""

revision = '0375_fix_service_name'
down_revision = '0374_fix_reg_template_history'

from alembic import op
from flask import current_app

service_id = current_app.config['NOTIFY_SERVICE_ID']


def upgrade():
    op.get_bind()
    
    # modify name of default service user in services
    # table_name = 'services'
    # col = 'name'
    # val = 'US Notify'
    # select_by_col = 'id'
    # select_by_val = service_id
    op.execute("update services set name='US Notify' where id = '{}'".format(service_id))
    
    # table_name = 'services_history'
    op.execute("update services_history set name='US Notify' where id = '{}'".format(service_id))
    

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
