"""

Revision ID: 0378_add_org_names
Revises: 0377_add_inbound_sms_number
Create Date: 2022-09-23 20:04:00.766980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0378_add_org_names'
down_revision = '0377_add_inbound_sms_number'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind()

    op.execute("TRUNCATE TABLE organisation_types CASCADE;")
    op.execute("INSERT INTO organisation_types VALUES ('state','f','250000'),('federal','f','250000'),('other','f','250000');")
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
