"""

Revision ID: 0393_remove_crown
Revises: 0392_drop_letter_permissions
Create Date: 2023-04-10 14:13:38.207790

"""
import sqlalchemy as sa
from alembic import op

revision = "0393_remove_crown"
down_revision = "0392_drop_letter_permissions"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organisation", "crown")
    op.drop_column("organisation_types", "is_crown")
    op.drop_column("services", "crown")
    op.drop_column("services_history", "crown")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "services_history",
        sa.Column("crown", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "services", sa.Column("crown", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "organisation_types",
        sa.Column("is_crown", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "organisation",
        sa.Column("crown", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
