"""empty message

Revision ID: 0010_events_table
Revises: 0009_created_by_for_jobs
Create Date: 2016-04-26 13:08:42.892813

"""

# revision identifiers, used by Alembic.
revision = '0399_remove_research_mode'
down_revision = '0398_agreements_table'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'research_mode')
    op.drop_column('services_history', 'research_mode')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('research_mode', sa.Boolean(), nullable=False))
    op.add_column('services_history', sa.Column('research_mode', sa.Boolean(), nullable=False))

    ### end Alembic commands ###