"""

Revision ID: 0410_remove_phone_columns
Revises: 0409_fix_service_name

"""
from sqlalchemy import text

down_revision = "0409_fix_service_name"
revision = "0410_remove_phone_columns"

from alembic import op
from flask import current_app


def upgrade():
    op.drop_column("notifications", "normalised_to")
    op.drop_column("notifications", "to")


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
