---
name: Restage apps

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment needs to be restaged"
        required: true
        default: staging
        type: environment

jobs:
  restage_apps:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        app: ["api", "admin"]
    steps:
      - name: Restage ${{matrix.app}}
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CLOUDGOV_USERNAME }}
          cf_password: ${{ secrets.CLOUDGOV_PASSWORD }}
          cf_org: gsa-tts-benefits-studio
          cf_space: notify-${{ inputs.environment }}
          cf_command: >-
            push -f manifest.yml
            --vars-file deploy-config/${{inputs.environment}}.yml
            --var DANGEROUS_SALT="$DANGEROUS_SALT"
            --var SECRET_KEY="$SECRET_KEY"
            --var ADMIN_CLIENT_SECRET="$ADMIN_CLIENT_SECRET"
            --var NEW_RELIC_LICENSE_KEY="$NEW_RELIC_LICENSE_KEY"
            --var NOTIFY_E2E_TEST_EMAIL="$NOTIFY_E2E_TEST_EMAIL"
            --var NOTIFY_E2E_TEST_PASSWORD="$NOTIFY_E2E_TEST_PASSWORD"
            --var LOGIN_DOT_GOV_REGISTRATION_URL="$LOGIN_DOT_GOV_REGISTRATION_URL"
            --strategy rolling
          command: "cf restage --strategy rolling notify-${{matrix.app}}-${{inputs.environment}}"
      - name: Restage ${{matrix.app}} egress
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CLOUDGOV_USERNAME }}
          cf_password: ${{ secrets.CLOUDGOV_PASSWORD }}
          cf_org: gsa-tts-benefits-studio
          cf_space: notify-${{ inputs.environment }}-egress

          command: |
            cf restage --strategy rolling egress-proxy-notify-${{matrix.app}}-${{inputs.environment}}
